apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    k8s-app: {{ .Chart.Name }}
  name: {{ include "aws-ssm.fullname" . }}
spec:
  selector:
    matchLabels:
      k8s-app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        k8s-app: {{ .Chart.Name }}
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default 'latest' }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: {{ .Chart.Name }}
        command: ["/bin/bash","-c","echo '* * * * * root rpm -e amazon-ssm-agent-2.3.1550.0-1.x86_64 && yum install -y https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/linux_amd64/amazon-ssm-agent.rpm && systemctl restart amazon-ssm-agent && rm -rf /etc/cron.d/ssmstart' > /etc/cron.d/ssmstart && echo 'Successfully installed SSM agent'"]
        securityContext:
          allowPrivilegeEscalation: true
        volumeMounts:
        - mountPath: /etc/cron.d
          name: cronfile    
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        resources:
      {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      - name: cronfile
        hostPath:
          path: /etc/cron.d
          type: Directory
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
